services:
  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./rules.yml:/etc/prometheus/rules.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'
    healthcheck:
      test: ["CMD", "wget", "http://localhost:9090"]
      interval: 10s
      timeout: 3s
      retries: 20

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    pid: host
    ports:
      - '9100:9100'
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro,rslave
    healthcheck:
      test: ["CMD", "wget", "http://localhost:9100"]
      interval: 10s
      timeout: 3s
      retries: 20
