version: "3.7"

x-name: &compose-project-name simple-lgtm

services:
  loki:
    container_name: loki
    image: "grafana/loki:3.3.0"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1",
        ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - data-loki:/loki
    restart: unless-stopped

  permission-init:
    container_name: permission-init
    image: &tempoImage grafana/tempo:2.6.1
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - data-tempo:/var/tempo

  tempo:
    container_name: tempo
    image: *tempoImage
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:3200/ready || exit 1",
        ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["-config.file=/etc/tempo.yaml"]
    restart: unless-stopped
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
      - data-tempo:/tmp/tempo
    depends_on:
      - permission-init

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.0.1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/-/healthy"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - data-prometheus:/prometheus
    command:
      # Standard config
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      # Additional config
      - "--storage.tsdb.retention.size=2GB"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=exemplar-storage"

  grafana:
    container_name: grafana
    image: grafana/grafana:11.3.1
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_USERS_VIEWERS_CAN_EDIT: "true"
      GF_USERS_EDITORS_CAN_ADMIN: "true"
      GF_INSTALL_PLUGINS: "https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-traces-app"
      GF_FEATURE_TOGGLES_ENABLE: "tempoSearch tempoBackendSearch tempoServiceGraph tempoApmTable traceToMetrics newTraceViewHeader metricsSummary correlations traceToProfiles tracesEmbeddedFlameGraph"
    volumes:
      - ./provisioning/:/etc/grafana/provisioning/
      - data-grafana:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - loki
      - tempo
      - prometheus

  alloy:
    container_name: alloy
    image: grafana/alloy:v1.5.0
    ports:
      - "12345:12345"
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    volumes:
      - "./config.alloy:/etc/alloy/config.alloy"
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=public-preview",
      "/etc/alloy/config.alloy",
    ]
    depends_on:
      - prometheus
      - loki
      - tempo
    restart: unless-stopped

volumes:
  data-loki:
  data-tempo:
  data-prometheus:
  data-grafana:
